### ISSUE TITLE
Wrong error on Unique constraints

### ISSUE THREAD

**Issue by FrauElster** [glebarez/sqlite#124]
The library does not return the [ErrDuplicatedKey](https://gorm.io/docs/error_handling.html) as gorm documents, but just returns the go-sqlite 2067 ("constraint failed: UNIQUE constraint failed: users.username (2067)") error. 

To be compliant, there should be a mapping of the errors so that one can check `errors.Is(err, gorm.ErrDuplicatedKey)` independently of the used database driver.

**Comment by FrauElster** [comment]
I think it is actually fixed in [here](https://github.com/glebarez/sqlite/blob/084ab1e90be6c9671ae476c5b45886347c8dc715/sqlite.go#L242), just not released yet

**Comment by glebarez** [comment]
released with https://github.com/glebarez/sqlite/releases/tag/v1.11.0
please check
