### ISSUE TITLE
invalid operation: limit.Limit > 0 (mismatched types *int and untyped int)

### ISSUE THREAD

**Issue by bambuo** [glebarez/sqlite#128]
`
C:\Users\xxx\go\pkg\mod\gorm.io\driver\sqlite@v1.3.6\sqlite.go:100:22: invalid operation: limit.Limit > 0 (mismatched types *int and untyped int)

C:\Users\xxx\go\pkg\mod\gorm.io\driver\sqlite@v1.3.6\sqlite.go:101:24: invalid operation: limit.Limit <= 0 (mismatched types *int and untyped int)

C:\Users\xxx\go\pkg\mod\gorm.io\driver\sqlite@v1.3.6\sqlite.go:102:21: cannot use -1 (untyped int constant) as *int value in assignment

C:\Users\xxx\go\pkg\mod\gorm.io\driver\sqlite@v1.3.6\sqlite.go:105:39: cannot use limit.Limit (variable of type *int) as int value in argument to strconv.Itoa
`

**Comment by soon95** [comment]
Hello, I have a similar problem. How did you solve it？
