### ISSUE TITLE
Still depends on CGO

### ISSUE THREAD

**Issue by lekoOwO** [glebarez/sqlite#21]
In https://github.com/glebarez/sqlite/blob/ed824cfc7fe069e4285d9ac6336da280ce28d9c0/go.sum#L17 , seems that it still depends on `mattn/go-sqlite3`, which can't run without CGO enabled.

**Comment by glebarez** [comment]
This dep is used purely in tests against mattn's CGo driver.
It is therefore not used during build of this driver itself.
You may try it yourself, e.g. build your application (which uses this driver) in the environment that lacks C compiler (golang-alpine docker image, for example).

More info in upstream issue:
https://gitlab.com/cznic/sqlite/-/issues/69

**Comment by lekoOwO** [comment]
> This dep is used purely in tests against mattn's CGo driver.
> It is therefore not used during build of this driver itself.
> You may try it yourself, e.g. build your application (which uses this driver) in the environment that lacks C compiler (golang-alpine docker image, for example).
> 
> More info in upstream issue:
> https://gitlab.com/cznic/sqlite/-/issues/69

The reason that i filed this issue is that when I tried to build by app using GitHub Action with this dep, running the binary gives that "... go-sqlite3 requires CGO_ENABLED=1 blah blah..." 🤔

**Comment by lekoOwO** [comment]
Oh, I've found that it's GitHub's CDN cache issue... Thanks!
