### ISSUE TITLE
Is it possible to set a journal_mode?

### ISSUE THREAD

**Issue by alexkmbk** [glebarez/sqlite#27]

**Comment by glebarez** [comment]
sure, see https://github.com/glebarez/go-sqlite#settings-pragmas-in-connection-string

**Comment by alexkmbk** [comment]
Yeah, thank you! it really works.

**Comment by alexkmbk** [comment]
> sure, see https://github.com/glebarez/go-sqlite#settings-pragmas-in-connection-string

but if I would like to set both: shared cache and journal mode, should I use the syntax like this:
"?cache=shared&_pragma=journal_mode(MEMORY)" ?

**Comment by glebarez** [comment]
> > sure, see https://github.com/glebarez/go-sqlite#settings-pragmas-in-connection-string
> 
> 
> 
> but if I would like to set both: shared cache and journal mode, should I use the syntax like this:
> 
> "?cache=shared&_pragma=journal_mode(MEMORY)" ?

'''cache''' option is parsed by sqlite itself. According to [docs](https://www.sqlite.org/c3ref/open.html) (see URI Filenames ssction), you must prepend your connection string with '''file:''' to enable this parsing

**Comment by alexkmbk** [comment]
> > > sure, see https://github.com/glebarez/go-sqlite#settings-pragmas-in-connection-string
> > 
> > 
> > but if I would like to set both: shared cache and journal mode, should I use the syntax like this:
> > "?cache=shared&_pragma=journal_mode(MEMORY)" ?
> 
> `cache` option is parsed by sqlite itself. According to [docs](https://www.sqlite.org/c3ref/open.html) (see URI Filenames section), you must prepend your connection string with `file:` to enable this parsing.
> 
> So, in your case you should use it like this: `"file:data.db?cache=shared&_pragma=journal_mode(MEMORY)"` or `"file::memory:?cache=shared&_pragma=journal_mode(MEMORY)"` (for in-memory DB)

yes, thanks!
