### ISSUE TITLE
驱动不支持windows, 386

### ISSUE THREAD

**Issue by guohuiyuan** [glebarez/sqlite#71]
如图
![image](https://user-images.githubusercontent.com/54976075/203199513-190a23ae-4bb9-47de-94a6-d2445841143b.png)

**Comment by glebarez** [comment]
Hello, the Windows on 386 is not (yet?) supported by [underlying SQLite implementation](https://gitlab.com/cznic/sqlite).
Checkout their project, that's the place to land an issue for it.
