### ISSUE TITLE
[FEAT] Support CREATE VIRTUAL TABLE / FTS5

### ISSUE THREAD

**Issue by tonytony2020** [glebarez/sqlite#72]
This package seems not support CREATE VIRTUAL TABLE / FTS5, test code
https://go.dev/play/p/PxjDDoIn1N2

It would be nice to have support for the CREATE VIRTUAL TABLE feature,
Thanks.

ref
 - https://www.sqlite.org/fts5.html

**Comment by glebarez** [comment]
Hello, FTS5 is enabled by default.
The problem in your code is that ```Raw``` doesn't execute the query, you need ```Exec```:
```go
sql := `CREATE VIRTUAL TABLE IF NOT EXISTS ft using fts5(id,name);`
err = db.Exec(sql).Error
```

**Comment by tonytony2020** [comment]
> Hello, FTS5 is enabled by default. The problem in your code is that `Raw` doesn't execute the query, you need `Exec`:
> 
> ```go
> sql := `CREATE VIRTUAL TABLE IF NOT EXISTS ft using fts5(id,name);`
> err = db.Exec(sql).Error
> ```

Thanks!
